### ISSUE TITLE
Framework agnostic package

### ISSUE THREAD

**Issue by layerok** [tonysm/globalid-laravel#6]
Hello. I have one simple request for you. I'll start with the task that I had. The task was to extract the `modelId` from the globalid. I searched for libraries that can help me but only found your library but it's too big for my simple task and I don't use laravel. In my case, the only thing needed to solve my problem was the ```parse``` method of the ```URI\GID``` class. So my request is to move ```URI\GID``` to a separate package so that people like me can use it for such small tasks. What do you think?

**Comment by tonysm** [comment]
Not sure I follow. If you need to extract the `modelId`, it means you're already using the package in your project, right? In that case, you can already use the class and methods you want since they are already available. Now, if you're not using the package in your project, what's the use case exactly?

Sorry, but I have no plans of extracting those classes out and maintaining another package. But feel free to take only the needed classes and host them on your project or something! I'm also glad to help if you want to share more context on your use case.
